import Head from 'next/head'
import Header from '@/component/Header'
import { useRouter } from 'next/router'
import Faqs from '@/component/Faqs';



export default function Apply() {
  const router = useRouter();
  const country = router.query.country;
  const loggedIn = router.query.loggedIn;
  const onStartVisaApplication = () => {
    alert(loggedIn)
    if(loggedIn){
      router.push({
        pathname: '/apply/visaform',
        query: { country: country,loggedIn : loggedIn }
    }, '/apply');
    }else{
      router.push({
        pathname: '/signin',
        query: {}
    }, '/sigin');
    }
    

  };
  return (
    <>
      <Head>
        <title>Apply Visa to</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container-fluid">
        <div className='row'>
          <div className='col-md-3'>
            Let's go <h1  >{country}</h1>
          </div>
        </div>
        <hr/>
        <button onClick={onStartVisaApplication} style={{width:'100%'}} type="button" className="btn btn-primary">Start {country} visa journey </button>
        <hr/>
        <Faqs/>
      </div>
    </>
  )
}
