import Head from 'next/head'
import Header from '@/component/Header'
import { useRouter } from 'next/router'
import Faqs from '@/component/Faqs';
import { useState } from 'react';
import axios from 'axios';



export  function Apply({userDetailsData}) {
  const router = useRouter();
  const country = router.query.country;
  const loggedIn = router.query.loggedIn;
  const _id = router.query._id
  console.log(userDetailsData)
  

  const [firstName, setFirstName] = useState(userDetailsData ? userDetailsData.firstName : '');
  const [lastName, setLastName] = useState(userDetailsData ? userDetailsData.lastName : '');
  const [email, setEmail] = useState(userDetailsData ? userDetailsData.email : '');
  const [mobileNumber, setMobileNumber] = useState(userDetailsData ? userDetailsData.mobileNumber : '');
  const [dateOfBirth, setDateOfBirth] = useState(userDetailsData ? userDetailsData.dateOfBirth : '');
  const [houseNumber, setHouseNumber] = useState(userDetailsData ? userDetailsData.houseNumber : '');
  const [streetName, setStreetName] = useState(userDetailsData ? userDetailsData.streetName : '');
  const [city, setCity] = useState(userDetailsData ? userDetailsData.city : '');
  const [state, setState] = useState(userDetailsData ? userDetailsData.state : '');
  const [pincode, setPincode] = useState(userDetailsData ? userDetailsData.pincode : '');
  
  

  async function addUserDetails(e) {
    e.preventDefault()
    const userDetatails = {
      firstName,
      lastName,
      email,
      mobileNumber,
      dateOfBirth,
      houseNumber,
      streetName,
      city,
      state,
      pincode
    }
    try {
      await axios.post('/api/apply/visaform', userDetatails);
      alert("User details added successfully");
    } catch (error) {
      alert("Error while adding User details...")
    }
  }

  return (
    <>
      <Head>
        <title>Apply Visa to</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container-fluid">
        <div className='row'>
          <div className='col-md-3'>
            Let's go <h1  >{country}</h1>
          </div>
        </div>
        <hr />
        <form className="row g-3">
          <div className="col-md-6">
            <label htmlFor="firstName" className="form-label">First name(as on Passport)</label>
            <input value={firstName} onChange={(e) => { setFirstName(e.target.value) }} type="text" className="form-control" id="firstName" />
          </div>
          <div className="col-md-6">
            <label htmlFor="lastName" className="form-label">Last name (as on Passport)</label>
            <input value={lastName} onChange={(e) => { setLastName(e.target.value) }} type="text" className="form-control" id="lastName" />
          </div>
          <div className="col-6">
            <label htmlFor="email" className="form-label">Email</label>
            <input value={email} onChange={(e) => { setEmail(e.target.value) }} type="email" className="form-control" id="email" />
          </div>
          <div className="col-6">
            <label htmlFor="mobileNumber" className="form-label">Mobile number</label>
            <input value={mobileNumber} onChange={(e) => { setMobileNumber(e.target.value) }} type="text" className="form-control" id="mobileNumber" />
          </div>
          <div className="col-md-6">
            <label htmlFor="dateOfBirth" className="form-label">Date of birth</label>
            <input value={dateOfBirth} onChange={(e) => { setDateOfBirth(e.target.value) }} type="text" className="form-control" id="dateOfBirth" />
          </div>


          <div className="col-6">
            <label htmlFor="houseNumber" className="form-label">Flat/House No.</label>
            <input value={houseNumber} onChange={(e) => { setHouseNumber(e.target.value) }} type="input" className="form-control" id="houseNumber" />
          </div>
          <div className="col-6">
            <label htmlFor="streetName" className="form-label">Society/Street Name</label>
            <input value={streetName} onChange={(e) => { setStreetName(e.target.value) }} type="text" className="form-control" id="streetName" />
          </div>
          <div className="col-md-6">
            <label htmlFor="city" className="form-label">City</label>
            <input value={city} onChange={(e) => { setCity(e.target.value) }} type="text" className="form-control" id="city" />
          </div>


          <div className="col-md-6">
            <label htmlFor="state" className="form-label">State</label>
            <select value={state} onChange={(e) => { setState(e.target.value) }} id="state" className="form-select">
              <option defaultValue>Choose...</option>
              <option value="Andhra Pradesh">Andhra Pradesh</option>
              <option value="Andhra Pradesh">Arunachal Pradesh</option>
              <option value="Andhra Pradesh">Assam</option>
            </select>
          </div>
          <div className="col-md-6">
            <label htmlFor="pincode" className="form-label">Pincode</label>
            <input value={pincode} onChange={(e) => { setPincode(e.target.value) }} type="text" className="form-control" id="pincode" />
          </div>

          <div className="col-12">
            <button onClick={addUserDetails} type="submit" className="btn btn-primary">Save</button>
          </div>
        </form>
      </div>
    </>
  )
}

export async function getServerSideProps(context) {
  const _id = context.query._id;
  const isEdit = context.query.isEdit;
  if(isEdit){
    try {
      const params = {
        id: _id,
        isEdit: isEdit
      };
      //const response = await axios.get("http://localhost:3000/api/apply/visaform",{params:params});
      return {
        props: {
          userDetailsData: {
            "_id": "649538ac1c526f6184e88293",
            "firstName": "sdsd",
            "lastName": "sd",
            "email": "rt@gmail.com",
            "mobileNumber": "d",
            "dateOfBirth": "sd",
            "houseNumber": "",
            "streetName": "w",
            "city": "",
            "state": "Andhra Pradesh",
            "pincode": "",
            "__v": 0
        },
        isEdit:isEdit
        },
      }
    } catch (error) {
      console.log(error)
    }
  }else{
    return {
      props: {
      },
    }
  }
}

export default Apply

