import Head from 'next/head'
import Header from '@/component/Header'
import DestinationAutocomplete from '@/component/DestinationAutocomplete'
import { useRouter } from 'next/router';



export default function Home() {
  const router = useRouter();
  const loggedIn = router.query.loggedIn
  return (
    <>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container-fluid">
        <div className='row'>
          <div className=" col-md-4"></div>
          <div className="mb-3 col-md-4">
            <DestinationAutocomplete loggedIn={loggedIn}/>
          </div>
        </div>
        <div className='destination-container'>
          <span className="badge rounded-pill text-bg-primary">Afghanistan</span>
          <span className="badge rounded-pill text-bg-secondary">Albania</span>
          <span className="badge rounded-pill text-bg-success">Algeria</span>
          <span className="badge rounded-pill text-bg-danger">Andorra</span>
          <span className="badge rounded-pill text-bg-warning">Angola</span>
          <span className="badge rounded-pill text-bg-info">Antigua and Barbuda</span>
          <span className="badge rounded-pill text-bg-light">Argentina</span>
          <span className="badge rounded-pill text-bg-dark">Armenia</span>
        </div>
      </div>
    </>
  )
}
