import Head from 'next/head'
import Header from '@/component/Header'
import { useRouter } from 'next/router';
import axios from 'axios';
import React from 'react';
import UserDetailItem from '@/component/UserDetailItem';



export default function VisaApplications({ userDetailsData }) {
  const router = useRouter();
  const loggedIn = router.query.loggedIn
  console.log(userDetailsData)

  const userDetailsItems = userDetailsData.map((userDetail) => {
    return <UserDetailItem key={userDetail._id} userDetail={userDetail} />
  });

  return (
    <>
      <Head>
        <title>Visa Application Dashboard </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container-fluid">
        <div className='row'>
        {userDetailsItems}
        </div>
      </div>
    </>
  )
}

export async function getStaticProps() {
  try {
    //const response = await axios.get("http://localhost:3000/api/apply/visaform");
    return {
      props: {
        userDetailsData: [{
          "_id": "649538ac1c526f6184e88293",
          "firstName": "sdsd",
          "lastName": "sd",
          "email": "rt@gmail.com",
          "mobileNumber": "d",
          "dateOfBirth": "sd",
          "houseNumber": "",
          "streetName": "w",
          "city": "",
          "state": "Andhra Pradesh",
          "pincode": "",
          "__v": 0
      }]
      }
    }
  } catch (error) {
    console.log(error)
  }
}
